FROM node:20-alpine AS builder
WORKDIR /app
COPY . .
# not sure why but the production image only seems to know about env variables if they are set in the docker compose as build args
# ARG BACKEND_ADDRESS
# ENV BACKEND_ADDRESS $BACKEND_ADDRESS
RUN npm install
RUN npm run build

FROM nginx:1.25.4-alpine-slim AS prod
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf  /etc/nginx/conf.d
EXPOSE 3002
CMD ["nginx", "-g", "daemon off;"]