version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # no env_file arg here since Vite requires it own .env file in its own directory to expose env vars to client
    networks:
      - network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    # Docker always reaches for the .env file to assign the values dynamically here
    # so Docker will use the root .env file and we will give the backend a different .env file to use 
    # to access node_env, the correct port, etc
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    networks:
      - network
networks:
  network: