version: "3.9"
services:
  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend-prod
    restart: always
    ports:
      - ${FRONTEND_PORT_PROD}:${FRONTEND_PORT_PROD}
    networks:
      - network
  
  backend-prod:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend-prod
    restart: always
    ports:
      - ${BACKEND_PORT_PROD}:${BACKEND_PORT_PROD}
    # not supposed to use .env in prod but we can take care of this later
    # ALSO IMPORTANT DOCKER DOES NOT SEEM TO IDENTIFY USING AN .ENV.PRODUCTION FILE HERE
    env_file:
      - .env
    networks:
      - network
networks:
  network: